// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package greeter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Greeting             string   `protobuf:"bytes,2,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type CinemaRequest struct {
	Column               string   `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CinemaRequest) Reset()         { *m = CinemaRequest{} }
func (m *CinemaRequest) String() string { return proto.CompactTextString(m) }
func (*CinemaRequest) ProtoMessage()    {}
func (*CinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{2}
}

func (m *CinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemaRequest.Unmarshal(m, b)
}
func (m *CinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemaRequest.Marshal(b, m, deterministic)
}
func (m *CinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemaRequest.Merge(m, src)
}
func (m *CinemaRequest) XXX_Size() int {
	return xxx_messageInfo_CinemaRequest.Size(m)
}
func (m *CinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CinemaRequest proto.InternalMessageInfo

func (m *CinemaRequest) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *CinemaRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CinemaData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rows                 int32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	RowLength            int32    `protobuf:"varint,3,opt,name=rowLength,proto3" json:"rowLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CinemaData) Reset()         { *m = CinemaData{} }
func (m *CinemaData) String() string { return proto.CompactTextString(m) }
func (*CinemaData) ProtoMessage()    {}
func (*CinemaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{3}
}

func (m *CinemaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemaData.Unmarshal(m, b)
}
func (m *CinemaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemaData.Marshal(b, m, deterministic)
}
func (m *CinemaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemaData.Merge(m, src)
}
func (m *CinemaData) XXX_Size() int {
	return xxx_messageInfo_CinemaData.Size(m)
}
func (m *CinemaData) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemaData.DiscardUnknown(m)
}

var xxx_messageInfo_CinemaData proto.InternalMessageInfo

func (m *CinemaData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CinemaData) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *CinemaData) GetRowLength() int32 {
	if m != nil {
		return m.RowLength
	}
	return 0
}

type CinemaResponse struct {
	Data                 []*CinemaData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CinemaResponse) Reset()         { *m = CinemaResponse{} }
func (m *CinemaResponse) String() string { return proto.CompactTextString(m) }
func (*CinemaResponse) ProtoMessage()    {}
func (*CinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{4}
}

func (m *CinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemaResponse.Unmarshal(m, b)
}
func (m *CinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemaResponse.Marshal(b, m, deterministic)
}
func (m *CinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemaResponse.Merge(m, src)
}
func (m *CinemaResponse) XXX_Size() int {
	return xxx_messageInfo_CinemaResponse.Size(m)
}
func (m *CinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CinemaResponse proto.InternalMessageInfo

func (m *CinemaResponse) GetData() []*CinemaData {
	if m != nil {
		return m.Data
	}
	return nil
}

type MovieRequest struct {
	Column               string   `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieRequest) Reset()         { *m = MovieRequest{} }
func (m *MovieRequest) String() string { return proto.CompactTextString(m) }
func (*MovieRequest) ProtoMessage()    {}
func (*MovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{5}
}

func (m *MovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieRequest.Unmarshal(m, b)
}
func (m *MovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieRequest.Marshal(b, m, deterministic)
}
func (m *MovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieRequest.Merge(m, src)
}
func (m *MovieRequest) XXX_Size() int {
	return xxx_messageInfo_MovieRequest.Size(m)
}
func (m *MovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MovieRequest proto.InternalMessageInfo

func (m *MovieRequest) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *MovieRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MovieData struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieData) Reset()         { *m = MovieData{} }
func (m *MovieData) String() string { return proto.CompactTextString(m) }
func (*MovieData) ProtoMessage()    {}
func (*MovieData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{6}
}

func (m *MovieData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieData.Unmarshal(m, b)
}
func (m *MovieData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieData.Marshal(b, m, deterministic)
}
func (m *MovieData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieData.Merge(m, src)
}
func (m *MovieData) XXX_Size() int {
	return xxx_messageInfo_MovieData.Size(m)
}
func (m *MovieData) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieData.DiscardUnknown(m)
}

var xxx_messageInfo_MovieData proto.InternalMessageInfo

func (m *MovieData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type MovieResponse struct {
	Data                 []*MovieData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MovieResponse) Reset()         { *m = MovieResponse{} }
func (m *MovieResponse) String() string { return proto.CompactTextString(m) }
func (*MovieResponse) ProtoMessage()    {}
func (*MovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{7}
}

func (m *MovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieResponse.Unmarshal(m, b)
}
func (m *MovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieResponse.Marshal(b, m, deterministic)
}
func (m *MovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieResponse.Merge(m, src)
}
func (m *MovieResponse) XXX_Size() int {
	return xxx_messageInfo_MovieResponse.Size(m)
}
func (m *MovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MovieResponse proto.InternalMessageInfo

func (m *MovieResponse) GetData() []*MovieData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReservationRequest struct {
	Column               string   `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservationRequest) Reset()         { *m = ReservationRequest{} }
func (m *ReservationRequest) String() string { return proto.CompactTextString(m) }
func (*ReservationRequest) ProtoMessage()    {}
func (*ReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{8}
}

func (m *ReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationRequest.Unmarshal(m, b)
}
func (m *ReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationRequest.Marshal(b, m, deterministic)
}
func (m *ReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationRequest.Merge(m, src)
}
func (m *ReservationRequest) XXX_Size() int {
	return xxx_messageInfo_ReservationRequest.Size(m)
}
func (m *ReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationRequest proto.InternalMessageInfo

func (m *ReservationRequest) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *ReservationRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ReservationData struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservationData) Reset()         { *m = ReservationData{} }
func (m *ReservationData) String() string { return proto.CompactTextString(m) }
func (*ReservationData) ProtoMessage()    {}
func (*ReservationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{9}
}

func (m *ReservationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationData.Unmarshal(m, b)
}
func (m *ReservationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationData.Marshal(b, m, deterministic)
}
func (m *ReservationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationData.Merge(m, src)
}
func (m *ReservationData) XXX_Size() int {
	return xxx_messageInfo_ReservationData.Size(m)
}
func (m *ReservationData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationData.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationData proto.InternalMessageInfo

func (m *ReservationData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type ReservationResponse struct {
	Data                 []*ReservationData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReservationResponse) Reset()         { *m = ReservationResponse{} }
func (m *ReservationResponse) String() string { return proto.CompactTextString(m) }
func (*ReservationResponse) ProtoMessage()    {}
func (*ReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{10}
}

func (m *ReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationResponse.Unmarshal(m, b)
}
func (m *ReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationResponse.Marshal(b, m, deterministic)
}
func (m *ReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationResponse.Merge(m, src)
}
func (m *ReservationResponse) XXX_Size() int {
	return xxx_messageInfo_ReservationResponse.Size(m)
}
func (m *ReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationResponse proto.InternalMessageInfo

func (m *ReservationResponse) GetData() []*ReservationData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ShowingRequest struct {
	Column               string   `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowingRequest) Reset()         { *m = ShowingRequest{} }
func (m *ShowingRequest) String() string { return proto.CompactTextString(m) }
func (*ShowingRequest) ProtoMessage()    {}
func (*ShowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{11}
}

func (m *ShowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowingRequest.Unmarshal(m, b)
}
func (m *ShowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowingRequest.Marshal(b, m, deterministic)
}
func (m *ShowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowingRequest.Merge(m, src)
}
func (m *ShowingRequest) XXX_Size() int {
	return xxx_messageInfo_ShowingRequest.Size(m)
}
func (m *ShowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowingRequest proto.InternalMessageInfo

func (m *ShowingRequest) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *ShowingRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ShowingData struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowingData) Reset()         { *m = ShowingData{} }
func (m *ShowingData) String() string { return proto.CompactTextString(m) }
func (*ShowingData) ProtoMessage()    {}
func (*ShowingData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{12}
}

func (m *ShowingData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowingData.Unmarshal(m, b)
}
func (m *ShowingData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowingData.Marshal(b, m, deterministic)
}
func (m *ShowingData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowingData.Merge(m, src)
}
func (m *ShowingData) XXX_Size() int {
	return xxx_messageInfo_ShowingData.Size(m)
}
func (m *ShowingData) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowingData.DiscardUnknown(m)
}

var xxx_messageInfo_ShowingData proto.InternalMessageInfo

func (m *ShowingData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type ShowingResponse struct {
	Data                 []*ShowingData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ShowingResponse) Reset()         { *m = ShowingResponse{} }
func (m *ShowingResponse) String() string { return proto.CompactTextString(m) }
func (*ShowingResponse) ProtoMessage()    {}
func (*ShowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{13}
}

func (m *ShowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowingResponse.Unmarshal(m, b)
}
func (m *ShowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowingResponse.Marshal(b, m, deterministic)
}
func (m *ShowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowingResponse.Merge(m, src)
}
func (m *ShowingResponse) XXX_Size() int {
	return xxx_messageInfo_ShowingResponse.Size(m)
}
func (m *ShowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowingResponse proto.InternalMessageInfo

func (m *ShowingResponse) GetData() []*ShowingData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserRequest struct {
	Column               string   `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{14}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *UserRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UserData struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{15}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type UserResponse struct {
	Data                 []*UserData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{16}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetData() []*UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
	proto.RegisterType((*CinemaRequest)(nil), "CinemaRequest")
	proto.RegisterType((*CinemaData)(nil), "CinemaData")
	proto.RegisterType((*CinemaResponse)(nil), "CinemaResponse")
	proto.RegisterType((*MovieRequest)(nil), "MovieRequest")
	proto.RegisterType((*MovieData)(nil), "MovieData")
	proto.RegisterType((*MovieResponse)(nil), "MovieResponse")
	proto.RegisterType((*ReservationRequest)(nil), "ReservationRequest")
	proto.RegisterType((*ReservationData)(nil), "ReservationData")
	proto.RegisterType((*ReservationResponse)(nil), "ReservationResponse")
	proto.RegisterType((*ShowingRequest)(nil), "ShowingRequest")
	proto.RegisterType((*ShowingData)(nil), "ShowingData")
	proto.RegisterType((*ShowingResponse)(nil), "ShowingResponse")
	proto.RegisterType((*UserRequest)(nil), "UserRequest")
	proto.RegisterType((*UserData)(nil), "UserData")
	proto.RegisterType((*UserResponse)(nil), "UserResponse")
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_e585294ab3f34af5) }

var fileDescriptor_e585294ab3f34af5 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdb, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x53, 0xda, 0x74, 0xeb, 0x97, 0x4b, 0x27, 0xaf, 0x42, 0x55, 0xc4, 0xa5, 0x98, 0x09,
	0x2a, 0x2e, 0x67, 0x22, 0x15, 0x4f, 0x03, 0x24, 0x2e, 0x12, 0x3c, 0xc0, 0x4b, 0x10, 0x7f, 0x40,
	0x00, 0xab, 0x8b, 0x94, 0xc6, 0x5b, 0xe2, 0xb6, 0xff, 0x3e, 0xaa, 0xed, 0x76, 0xf1, 0x98, 0xfa,
	0xd0, 0xb7, 0x38, 0xf1, 0xf7, 0x9d, 0xdf, 0xb1, 0xbf, 0x13, 0x44, 0xf3, 0x5a, 0x08, 0x25, 0x6a,
	0xba, 0xaa, 0xa5, 0x92, 0x9c, 0x23, 0xfc, 0x26, 0xca, 0x52, 0x66, 0xe2, 0x7a, 0x29, 0x1a, 0xc5,
	0x18, 0x7a, 0x55, 0xbe, 0x10, 0xe3, 0xce, 0xa4, 0x33, 0x1d, 0x64, 0xfa, 0x99, 0xbf, 0x44, 0x64,
	0xf7, 0x34, 0x57, 0xb2, 0x6a, 0x04, 0x4b, 0x70, 0xac, 0x5d, 0x8a, 0x6a, 0x3e, 0xbe, 0xa7, 0x37,
	0xee, 0xd6, 0xfc, 0x3d, 0xa2, 0xcf, 0x45, 0x25, 0x16, 0xf9, 0xd6, 0xf1, 0x3e, 0xfa, 0x7f, 0x64,
	0xb9, 0x5c, 0x54, 0xd6, 0xd3, 0xae, 0xd8, 0x08, 0xfe, 0x2a, 0x2f, 0x97, 0xc2, 0x3a, 0x98, 0x05,
	0xcf, 0x00, 0x23, 0xff, 0x92, 0xab, 0xfc, 0x2e, 0x9a, 0xcd, 0xbb, 0x5a, 0xae, 0x1b, 0x2d, 0xf3,
	0x33, 0xfd, 0xcc, 0x1e, 0x60, 0x50, 0xcb, 0xf5, 0x77, 0x51, 0xcd, 0xd5, 0xe5, 0xb8, 0xab, 0x3f,
	0xdc, 0xbc, 0xe0, 0x6f, 0x10, 0x6f, 0x91, 0x6c, 0x03, 0x8f, 0xd1, 0xfb, 0x9b, 0xab, 0x7c, 0xdc,
	0x99, 0x74, 0xa7, 0x41, 0x1a, 0xd0, 0x4d, 0xc9, 0x4c, 0x7f, 0xe0, 0xef, 0x10, 0xfe, 0x90, 0xab,
	0x42, 0x1c, 0xd6, 0xc4, 0x13, 0x0c, 0xb4, 0x5a, 0xf7, 0x30, 0x82, 0xaf, 0x0a, 0x55, 0x6e, 0x9b,
	0x30, 0x0b, 0x7e, 0x8e, 0xc8, 0x16, 0xb0, 0x48, 0x8f, 0x1c, 0x24, 0xd0, 0xce, 0xc0, 0x12, 0x7d,
	0x02, 0xcb, 0x44, 0x23, 0xea, 0x55, 0xae, 0x0a, 0x59, 0x1d, 0xc6, 0xf5, 0x1c, 0xc3, 0x96, 0xc7,
	0x1e, 0xba, 0x0b, 0x9c, 0x3a, 0xc5, 0x2c, 0xe3, 0x99, 0xc3, 0x78, 0x42, 0xb7, 0xcc, 0x2c, 0xe9,
	0x07, 0xc4, 0x3f, 0x2f, 0xe5, 0xba, 0xa8, 0xe6, 0x87, 0x51, 0x3e, 0x45, 0x60, 0xf5, 0x7b, 0x08,
	0x67, 0x18, 0xee, 0x8a, 0x58, 0xba, 0x89, 0x43, 0x17, 0x52, 0xcb, 0xc4, 0x92, 0x5d, 0x20, 0xf8,
	0xd5, 0x88, 0xfa, 0x30, 0xac, 0x09, 0x8e, 0x37, 0xe2, 0x3d, 0x4c, 0xaf, 0x11, 0x1a, 0x7b, 0x0b,
	0xf4, 0xd0, 0x01, 0x1a, 0xd0, 0x56, 0x6e, 0x68, 0xd2, 0x19, 0x8e, 0xbe, 0x9a, 0x59, 0x64, 0x53,
	0xf8, 0x7a, 0xc2, 0x58, 0x44, 0xed, 0x69, 0x4c, 0x62, 0x72, 0x06, 0x8f, 0x7b, 0x69, 0x8a, 0xbe,
	0x09, 0x2b, 0x9b, 0xa2, 0x9b, 0x89, 0x6b, 0x16, 0x93, 0x33, 0x6e, 0xc9, 0x90, 0xdc, 0xac, 0x73,
	0x2f, 0x3d, 0x87, 0xaf, 0xd3, 0xc4, 0x9e, 0x19, 0x49, 0x44, 0xed, 0x6c, 0x27, 0x31, 0x39, 0x49,
	0xe4, 0x5e, 0xfa, 0x11, 0x41, 0xeb, 0x6a, 0x59, 0x6a, 0x64, 0xa7, 0xf4, 0x7f, 0x00, 0x93, 0x11,
	0xdd, 0x11, 0x14, 0xee, 0xa5, 0x6f, 0x71, 0x64, 0xcf, 0x9f, 0xbd, 0x30, 0xf2, 0x21, 0xb9, 0xa9,
	0x48, 0x4e, 0xe8, 0xd6, 0x0d, 0x72, 0x2f, 0x7d, 0x85, 0xde, 0xe6, 0x94, 0xd8, 0x99, 0xd1, 0x84,
	0xd4, 0xba, 0xaf, 0x24, 0xa2, 0xf6, 0xf1, 0x72, 0xef, 0x77, 0x5f, 0xff, 0xc3, 0x66, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x90, 0x95, 0x52, 0x97, 0xd4, 0x04, 0x00, 0x00,
}
