// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package greeter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Greeting             string   `protobuf:"bytes,2,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type CinemaRequest struct {
	Column               string   `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CinemaRequest) Reset()         { *m = CinemaRequest{} }
func (m *CinemaRequest) String() string { return proto.CompactTextString(m) }
func (*CinemaRequest) ProtoMessage()    {}
func (*CinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{2}
}

func (m *CinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemaRequest.Unmarshal(m, b)
}
func (m *CinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemaRequest.Marshal(b, m, deterministic)
}
func (m *CinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemaRequest.Merge(m, src)
}
func (m *CinemaRequest) XXX_Size() int {
	return xxx_messageInfo_CinemaRequest.Size(m)
}
func (m *CinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CinemaRequest proto.InternalMessageInfo

func (m *CinemaRequest) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *CinemaRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CinemaData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rows                 int32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	RowLength            int32    `protobuf:"varint,3,opt,name=rowLength,proto3" json:"rowLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CinemaData) Reset()         { *m = CinemaData{} }
func (m *CinemaData) String() string { return proto.CompactTextString(m) }
func (*CinemaData) ProtoMessage()    {}
func (*CinemaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{3}
}

func (m *CinemaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemaData.Unmarshal(m, b)
}
func (m *CinemaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemaData.Marshal(b, m, deterministic)
}
func (m *CinemaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemaData.Merge(m, src)
}
func (m *CinemaData) XXX_Size() int {
	return xxx_messageInfo_CinemaData.Size(m)
}
func (m *CinemaData) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemaData.DiscardUnknown(m)
}

var xxx_messageInfo_CinemaData proto.InternalMessageInfo

func (m *CinemaData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CinemaData) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *CinemaData) GetRowLength() int32 {
	if m != nil {
		return m.RowLength
	}
	return 0
}

type CinemaResponse struct {
	Data                 []*CinemaData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CinemaResponse) Reset()         { *m = CinemaResponse{} }
func (m *CinemaResponse) String() string { return proto.CompactTextString(m) }
func (*CinemaResponse) ProtoMessage()    {}
func (*CinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{4}
}

func (m *CinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemaResponse.Unmarshal(m, b)
}
func (m *CinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemaResponse.Marshal(b, m, deterministic)
}
func (m *CinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemaResponse.Merge(m, src)
}
func (m *CinemaResponse) XXX_Size() int {
	return xxx_messageInfo_CinemaResponse.Size(m)
}
func (m *CinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CinemaResponse proto.InternalMessageInfo

func (m *CinemaResponse) GetData() []*CinemaData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
	proto.RegisterType((*CinemaRequest)(nil), "CinemaRequest")
	proto.RegisterType((*CinemaData)(nil), "CinemaData")
	proto.RegisterType((*CinemaResponse)(nil), "CinemaResponse")
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_e585294ab3f34af5) }

var fileDescriptor_e585294ab3f34af5 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x1b, 0xd3, 0x44, 0x3b, 0x35, 0x11, 0x06, 0x91, 0x10, 0x04, 0xcb, 0x9e, 0x02, 0xc2,
	0x82, 0xe9, 0xd9, 0x93, 0x82, 0x1e, 0x3c, 0xed, 0x1b, 0xac, 0x3a, 0xc4, 0x42, 0xb2, 0xdb, 0x6e,
	0x36, 0xf6, 0xf5, 0xc5, 0xc9, 0xd6, 0x1a, 0xe8, 0x6d, 0xfe, 0xfe, 0xf6, 0x9b, 0x6f, 0x21, 0x6b,
	0x1c, 0x91, 0x27, 0x27, 0xb7, 0xce, 0x7a, 0x2b, 0x04, 0x5c, 0xbe, 0x52, 0xdb, 0x5a, 0x45, 0xbb,
	0x81, 0x7a, 0x8f, 0x08, 0x73, 0xa3, 0x3b, 0x2a, 0xa2, 0x55, 0x54, 0x2d, 0x14, 0xc7, 0xe2, 0x1e,
	0xb2, 0x30, 0xd3, 0x6f, 0xad, 0xe9, 0x09, 0x4b, 0xb8, 0x60, 0xca, 0xc6, 0x34, 0xc5, 0x19, 0x0f,
	0xfe, 0xe5, 0xe2, 0x11, 0xb2, 0xa7, 0x8d, 0xa1, 0x4e, 0x1f, 0x88, 0x37, 0x90, 0x7e, 0xd8, 0x76,
	0xe8, 0x4c, 0x60, 0x86, 0x0c, 0xaf, 0x21, 0xf9, 0xd6, 0xed, 0x40, 0x81, 0x30, 0x26, 0x42, 0x01,
	0x8c, 0xeb, 0xcf, 0xda, 0xeb, 0x53, 0x6a, 0x7e, 0x6b, 0xce, 0xee, 0x7b, 0x5e, 0x4b, 0x14, 0xc7,
	0x78, 0x0b, 0x0b, 0x67, 0xf7, 0x6f, 0x64, 0x1a, 0xff, 0x55, 0xc4, 0xdc, 0x38, 0x16, 0xc4, 0x03,
	0xe4, 0x07, 0x49, 0xe1, 0x80, 0x3b, 0x98, 0x7f, 0x6a, 0xaf, 0x8b, 0x68, 0x15, 0x57, 0xcb, 0x7a,
	0x29, 0x8f, 0x4f, 0x2a, 0x6e, 0xd4, 0x6b, 0x38, 0x7f, 0x19, 0x7d, 0xc2, 0x0a, 0x12, 0xbe, 0x1e,
	0x33, 0xf9, 0xdf, 0xa9, 0x32, 0x97, 0x13, 0x53, 0xc4, 0xac, 0xae, 0x21, 0x1d, 0x41, 0x58, 0x41,
	0xac, 0x68, 0x87, 0xb9, 0x9c, 0x58, 0x51, 0x5e, 0xc9, 0xa9, 0x0e, 0x31, 0x7b, 0x4f, 0xf9, 0x1b,
	0xd6, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xce, 0x11, 0x17, 0x97, 0x01, 0x00, 0x00,
}
