// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CinemaRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CinemaRequest) Reset()         { *m = CinemaRequest{} }
func (m *CinemaRequest) String() string { return proto.CompactTextString(m) }
func (*CinemaRequest) ProtoMessage()    {}
func (*CinemaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *CinemaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemaRequest.Unmarshal(m, b)
}
func (m *CinemaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemaRequest.Marshal(b, m, deterministic)
}
func (m *CinemaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemaRequest.Merge(m, src)
}
func (m *CinemaRequest) XXX_Size() int {
	return xxx_messageInfo_CinemaRequest.Size(m)
}
func (m *CinemaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CinemaRequest proto.InternalMessageInfo

type CinemaData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rows                 int32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	RowLength            int32    `protobuf:"varint,3,opt,name=rowLength,proto3" json:"rowLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CinemaData) Reset()         { *m = CinemaData{} }
func (m *CinemaData) String() string { return proto.CompactTextString(m) }
func (*CinemaData) ProtoMessage()    {}
func (*CinemaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *CinemaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemaData.Unmarshal(m, b)
}
func (m *CinemaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemaData.Marshal(b, m, deterministic)
}
func (m *CinemaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemaData.Merge(m, src)
}
func (m *CinemaData) XXX_Size() int {
	return xxx_messageInfo_CinemaData.Size(m)
}
func (m *CinemaData) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemaData.DiscardUnknown(m)
}

var xxx_messageInfo_CinemaData proto.InternalMessageInfo

func (m *CinemaData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CinemaData) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *CinemaData) GetRowLength() int32 {
	if m != nil {
		return m.RowLength
	}
	return 0
}

type CinemaResponse struct {
	Data                 []*CinemaData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CinemaResponse) Reset()         { *m = CinemaResponse{} }
func (m *CinemaResponse) String() string { return proto.CompactTextString(m) }
func (*CinemaResponse) ProtoMessage()    {}
func (*CinemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *CinemaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemaResponse.Unmarshal(m, b)
}
func (m *CinemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemaResponse.Marshal(b, m, deterministic)
}
func (m *CinemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemaResponse.Merge(m, src)
}
func (m *CinemaResponse) XXX_Size() int {
	return xxx_messageInfo_CinemaResponse.Size(m)
}
func (m *CinemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CinemaResponse proto.InternalMessageInfo

func (m *CinemaResponse) GetData() []*CinemaData {
	if m != nil {
		return m.Data
	}
	return nil
}

type MovieRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieRequest) Reset()         { *m = MovieRequest{} }
func (m *MovieRequest) String() string { return proto.CompactTextString(m) }
func (*MovieRequest) ProtoMessage()    {}
func (*MovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *MovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieRequest.Unmarshal(m, b)
}
func (m *MovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieRequest.Marshal(b, m, deterministic)
}
func (m *MovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieRequest.Merge(m, src)
}
func (m *MovieRequest) XXX_Size() int {
	return xxx_messageInfo_MovieRequest.Size(m)
}
func (m *MovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MovieRequest proto.InternalMessageInfo

type MovieData struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieData) Reset()         { *m = MovieData{} }
func (m *MovieData) String() string { return proto.CompactTextString(m) }
func (*MovieData) ProtoMessage()    {}
func (*MovieData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *MovieData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieData.Unmarshal(m, b)
}
func (m *MovieData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieData.Marshal(b, m, deterministic)
}
func (m *MovieData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieData.Merge(m, src)
}
func (m *MovieData) XXX_Size() int {
	return xxx_messageInfo_MovieData.Size(m)
}
func (m *MovieData) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieData.DiscardUnknown(m)
}

var xxx_messageInfo_MovieData proto.InternalMessageInfo

func (m *MovieData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type MovieResponse struct {
	Data                 []*MovieData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MovieResponse) Reset()         { *m = MovieResponse{} }
func (m *MovieResponse) String() string { return proto.CompactTextString(m) }
func (*MovieResponse) ProtoMessage()    {}
func (*MovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *MovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieResponse.Unmarshal(m, b)
}
func (m *MovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieResponse.Marshal(b, m, deterministic)
}
func (m *MovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieResponse.Merge(m, src)
}
func (m *MovieResponse) XXX_Size() int {
	return xxx_messageInfo_MovieResponse.Size(m)
}
func (m *MovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MovieResponse proto.InternalMessageInfo

func (m *MovieResponse) GetData() []*MovieData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReservationRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservationRequest) Reset()         { *m = ReservationRequest{} }
func (m *ReservationRequest) String() string { return proto.CompactTextString(m) }
func (*ReservationRequest) ProtoMessage()    {}
func (*ReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6}
}

func (m *ReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationRequest.Unmarshal(m, b)
}
func (m *ReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationRequest.Marshal(b, m, deterministic)
}
func (m *ReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationRequest.Merge(m, src)
}
func (m *ReservationRequest) XXX_Size() int {
	return xxx_messageInfo_ReservationRequest.Size(m)
}
func (m *ReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationRequest proto.InternalMessageInfo

type ReservationData struct {
	ReservationID        int32    `protobuf:"varint,1,opt,name=reservationID,proto3" json:"reservationID,omitempty"`
	Showing              int32    `protobuf:"varint,2,opt,name=showing,proto3" json:"showing,omitempty"`
	Seats                int32    `protobuf:"varint,3,opt,name=seats,proto3" json:"seats,omitempty"`
	Booked               bool     `protobuf:"varint,4,opt,name=booked,proto3" json:"booked,omitempty"`
	User                 string   `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservationData) Reset()         { *m = ReservationData{} }
func (m *ReservationData) String() string { return proto.CompactTextString(m) }
func (*ReservationData) ProtoMessage()    {}
func (*ReservationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{7}
}

func (m *ReservationData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationData.Unmarshal(m, b)
}
func (m *ReservationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationData.Marshal(b, m, deterministic)
}
func (m *ReservationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationData.Merge(m, src)
}
func (m *ReservationData) XXX_Size() int {
	return xxx_messageInfo_ReservationData.Size(m)
}
func (m *ReservationData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationData.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationData proto.InternalMessageInfo

func (m *ReservationData) GetReservationID() int32 {
	if m != nil {
		return m.ReservationID
	}
	return 0
}

func (m *ReservationData) GetShowing() int32 {
	if m != nil {
		return m.Showing
	}
	return 0
}

func (m *ReservationData) GetSeats() int32 {
	if m != nil {
		return m.Seats
	}
	return 0
}

func (m *ReservationData) GetBooked() bool {
	if m != nil {
		return m.Booked
	}
	return false
}

func (m *ReservationData) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type ReservationResponse struct {
	Data                 []*ReservationData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReservationResponse) Reset()         { *m = ReservationResponse{} }
func (m *ReservationResponse) String() string { return proto.CompactTextString(m) }
func (*ReservationResponse) ProtoMessage()    {}
func (*ReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{8}
}

func (m *ReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationResponse.Unmarshal(m, b)
}
func (m *ReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationResponse.Marshal(b, m, deterministic)
}
func (m *ReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationResponse.Merge(m, src)
}
func (m *ReservationResponse) XXX_Size() int {
	return xxx_messageInfo_ReservationResponse.Size(m)
}
func (m *ReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationResponse proto.InternalMessageInfo

func (m *ReservationResponse) GetData() []*ReservationData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ShowingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowingRequest) Reset()         { *m = ShowingRequest{} }
func (m *ShowingRequest) String() string { return proto.CompactTextString(m) }
func (*ShowingRequest) ProtoMessage()    {}
func (*ShowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{9}
}

func (m *ShowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowingRequest.Unmarshal(m, b)
}
func (m *ShowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowingRequest.Marshal(b, m, deterministic)
}
func (m *ShowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowingRequest.Merge(m, src)
}
func (m *ShowingRequest) XXX_Size() int {
	return xxx_messageInfo_ShowingRequest.Size(m)
}
func (m *ShowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowingRequest proto.InternalMessageInfo

type ShowingData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cinema               string   `protobuf:"bytes,2,opt,name=cinema,proto3" json:"cinema,omitempty"`
	Movie                string   `protobuf:"bytes,3,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowingData) Reset()         { *m = ShowingData{} }
func (m *ShowingData) String() string { return proto.CompactTextString(m) }
func (*ShowingData) ProtoMessage()    {}
func (*ShowingData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{10}
}

func (m *ShowingData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowingData.Unmarshal(m, b)
}
func (m *ShowingData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowingData.Marshal(b, m, deterministic)
}
func (m *ShowingData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowingData.Merge(m, src)
}
func (m *ShowingData) XXX_Size() int {
	return xxx_messageInfo_ShowingData.Size(m)
}
func (m *ShowingData) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowingData.DiscardUnknown(m)
}

var xxx_messageInfo_ShowingData proto.InternalMessageInfo

func (m *ShowingData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShowingData) GetCinema() string {
	if m != nil {
		return m.Cinema
	}
	return ""
}

func (m *ShowingData) GetMovie() string {
	if m != nil {
		return m.Movie
	}
	return ""
}

type ShowingResponse struct {
	Data                 []*ShowingData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ShowingResponse) Reset()         { *m = ShowingResponse{} }
func (m *ShowingResponse) String() string { return proto.CompactTextString(m) }
func (*ShowingResponse) ProtoMessage()    {}
func (*ShowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{11}
}

func (m *ShowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowingResponse.Unmarshal(m, b)
}
func (m *ShowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowingResponse.Marshal(b, m, deterministic)
}
func (m *ShowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowingResponse.Merge(m, src)
}
func (m *ShowingResponse) XXX_Size() int {
	return xxx_messageInfo_ShowingResponse.Size(m)
}
func (m *ShowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowingResponse proto.InternalMessageInfo

func (m *ShowingResponse) GetData() []*ShowingData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{12}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

type UserData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{13}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserResponse struct {
	Users                []*UserData `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{14}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUsers() []*UserData {
	if m != nil {
		return m.Users
	}
	return nil
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{15}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CinemaRequest)(nil), "CinemaRequest")
	proto.RegisterType((*CinemaData)(nil), "CinemaData")
	proto.RegisterType((*CinemaResponse)(nil), "CinemaResponse")
	proto.RegisterType((*MovieRequest)(nil), "MovieRequest")
	proto.RegisterType((*MovieData)(nil), "MovieData")
	proto.RegisterType((*MovieResponse)(nil), "MovieResponse")
	proto.RegisterType((*ReservationRequest)(nil), "ReservationRequest")
	proto.RegisterType((*ReservationData)(nil), "ReservationData")
	proto.RegisterType((*ReservationResponse)(nil), "ReservationResponse")
	proto.RegisterType((*ShowingRequest)(nil), "ShowingRequest")
	proto.RegisterType((*ShowingData)(nil), "ShowingData")
	proto.RegisterType((*ShowingResponse)(nil), "ShowingResponse")
	proto.RegisterType((*UserRequest)(nil), "UserRequest")
	proto.RegisterType((*UserData)(nil), "UserData")
	proto.RegisterType((*UserResponse)(nil), "UserResponse")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 651 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4d, 0x6f, 0xd3, 0x4a,
	0x14, 0x8d, 0xdb, 0xa4, 0x8d, 0x8f, 0x63, 0xbb, 0x6f, 0x5a, 0x3d, 0x59, 0xd1, 0x53, 0x5f, 0x18,
	0x02, 0x04, 0x84, 0xa6, 0xe0, 0x2e, 0x91, 0x2a, 0x95, 0x56, 0x8a, 0x10, 0xb0, 0x31, 0xe2, 0x07,
	0xb8, 0xf5, 0xa8, 0xb5, 0xda, 0xc4, 0xc5, 0x33, 0x6d, 0x57, 0x6c, 0x58, 0xb2, 0x84, 0x3f, 0xc9,
	0xcf, 0x40, 0xf3, 0xe1, 0xc4, 0xd3, 0x02, 0xa5, 0xbb, 0x39, 0xf7, 0xde, 0x99, 0x73, 0xee, 0xf5,
	0x3d, 0x32, 0xa2, 0x19, 0x17, 0x22, 0x3f, 0xe1, 0x82, 0x5d, 0xd4, 0x95, 0xac, 0x68, 0x8c, 0xf0,
	0xa0, 0x9c, 0xf3, 0x59, 0x9e, 0xf1, 0x4f, 0x97, 0x5c, 0x48, 0x9a, 0x01, 0x26, 0x70, 0x98, 0xcb,
	0x9c, 0x10, 0x74, 0xe7, 0xf9, 0x8c, 0x27, 0xde, 0xc8, 0x9b, 0xf8, 0x99, 0x3e, 0xab, 0x58, 0x5d,
	0x5d, 0x8b, 0x64, 0x65, 0xe4, 0x4d, 0x7a, 0x99, 0x3e, 0x93, 0xff, 0xe0, 0xd7, 0xd5, 0xf5, 0x3b,
	0x3e, 0x3f, 0x91, 0xa7, 0xc9, 0xaa, 0x4e, 0x2c, 0x03, 0xf4, 0x25, 0xa2, 0x86, 0x44, 0x5c, 0x54,
	0x73, 0xc1, 0xc9, 0xff, 0xe8, 0x16, 0xb9, 0xcc, 0x13, 0x6f, 0xb4, 0x3a, 0x09, 0xd2, 0x80, 0x2d,
	0x29, 0x33, 0x9d, 0xa0, 0x11, 0x06, 0xef, 0xab, 0xab, 0x92, 0x37, 0xb2, 0x1e, 0xc0, 0xd7, 0x58,
	0xab, 0xda, 0x42, 0x4f, 0x96, 0xf2, 0xbc, 0x91, 0x65, 0x00, 0xdd, 0x41, 0x68, 0xaf, 0x58, 0x92,
	0x6d, 0x87, 0x04, 0x6c, 0xf1, 0x80, 0xe5, 0xd8, 0x02, 0xc9, 0xb8, 0xe0, 0xf5, 0x55, 0x2e, 0xcb,
	0x6a, 0xde, 0x30, 0x7d, 0xf7, 0x10, 0xb7, 0xc2, 0x9a, 0x70, 0x8c, 0xb0, 0x5e, 0x86, 0xde, 0x1c,
	0x6a, 0xe2, 0x5e, 0xe6, 0x06, 0x49, 0x82, 0x75, 0x71, 0x5a, 0x5d, 0x97, 0xf3, 0x13, 0x3b, 0x9b,
	0x06, 0x2a, 0xc1, 0x82, 0xe7, 0x52, 0xd8, 0xd1, 0x18, 0x40, 0xfe, 0xc5, 0xda, 0x51, 0x55, 0x9d,
	0xf1, 0x22, 0xe9, 0x8e, 0xbc, 0x49, 0x3f, 0xb3, 0x48, 0x0d, 0xf8, 0x52, 0xf0, 0x3a, 0xe9, 0x99,
	0xa1, 0xab, 0x33, 0x7d, 0x85, 0x4d, 0x47, 0xab, 0x6d, 0x71, 0xec, 0xb4, 0xb8, 0xc1, 0x6e, 0x08,
	0xb7, 0x8d, 0x6e, 0x20, 0xfa, 0x60, 0x94, 0x34, 0x4d, 0xbe, 0x45, 0x60, 0x23, 0xba, 0xbf, 0x08,
	0x2b, 0x65, 0x61, 0x9b, 0x5a, 0x29, 0x0b, 0xa5, 0xec, 0x58, 0x7f, 0x11, 0xdd, 0x88, 0x9f, 0x59,
	0xa4, 0xfa, 0x98, 0xa9, 0x21, 0xea, 0x3e, 0xfc, 0xcc, 0x00, 0xba, 0x8b, 0x78, 0xf1, 0xbc, 0xd5,
	0x35, 0x72, 0x74, 0x0d, 0x58, 0x8b, 0xcc, 0x6a, 0x0a, 0x11, 0x7c, 0x14, 0xbc, 0x6e, 0x04, 0x6d,
	0xa3, 0xaf, 0xe0, 0xef, 0x96, 0x8e, 0xee, 0x60, 0x60, 0xca, 0x17, 0x0b, 0xd4, 0x53, 0x73, 0x11,
	0x96, 0xc1, 0x67, 0xcd, 0xed, 0xcc, 0xc4, 0xe9, 0x1e, 0xfa, 0x8b, 0x62, 0xf5, 0x61, 0x2e, 0x8f,
	0x8f, 0xb9, 0x10, 0xfa, 0xcd, 0x7e, 0xd6, 0x40, 0x95, 0xb1, 0x86, 0xb0, 0x9d, 0x36, 0x30, 0xfd,
	0xea, 0x61, 0xcd, 0x6c, 0x25, 0x79, 0x04, 0x7f, 0xbf, 0x28, 0x2c, 0x68, 0xef, 0xea, 0xd0, 0x67,
	0x0d, 0x07, 0xed, 0x90, 0x09, 0x06, 0x87, 0xfc, 0x9c, 0x4b, 0x7e, 0x67, 0xe5, 0x0e, 0x30, 0xe5,
	0xd2, 0x64, 0x05, 0x89, 0x98, 0xe3, 0xc0, 0x61, 0xcc, 0x5c, 0xb3, 0xd0, 0x4e, 0xfa, 0xc5, 0x43,
	0x4f, 0x6f, 0x2f, 0x79, 0x88, 0xfe, 0x7e, 0x51, 0x98, 0x73, 0x6b, 0xa3, 0xdd, 0xf7, 0x1f, 0x23,
	0x30, 0x4a, 0xee, 0xa8, 0x7b, 0x0e, 0x7f, 0xca, 0xa5, 0x4e, 0x0a, 0x12, 0xb2, 0xb6, 0xe1, 0x86,
	0x11, 0x73, 0xcc, 0x44, 0x3b, 0xe9, 0x0f, 0x0f, 0x41, 0x6b, 0xbf, 0xc8, 0xae, 0xb2, 0x8f, 0x2e,
	0x6e, 0x47, 0x6f, 0xed, 0xa0, 0x4b, 0xf9, 0x02, 0xf1, 0xeb, 0xaa, 0x3a, 0xbb, 0xc7, 0x8d, 0x14,
	0xff, 0x98, 0x66, 0xee, 0x71, 0x67, 0x0f, 0xf1, 0x94, 0xb7, 0x65, 0x09, 0xb2, 0xc9, 0x6e, 0x7b,
	0x7d, 0xb8, 0xc5, 0x7e, 0x61, 0x2a, 0xda, 0x49, 0xbf, 0x79, 0x58, 0xb7, 0x2b, 0x4b, 0x9e, 0x00,
	0xfb, 0x45, 0xd1, 0x20, 0x67, 0x95, 0x5d, 0xd2, 0x67, 0x08, 0x8d, 0xd0, 0xbf, 0xa8, 0x4d, 0x11,
	0x4c, 0xb9, 0xb4, 0x69, 0x41, 0x62, 0xe6, 0xfa, 0x73, 0xb8, 0xc1, 0x6e, 0x38, 0x8a, 0x76, 0xd2,
	0xcf, 0xe8, 0xaa, 0x25, 0x27, 0x63, 0xe0, 0xa0, 0xe6, 0xb9, 0xe4, 0x1a, 0x2d, 0x37, 0xdf, 0x65,
	0x18, 0x03, 0x46, 0xcd, 0x1f, 0xab, 0x9e, 0xa2, 0x3f, 0xe5, 0x52, 0xe5, 0x04, 0x19, 0xb0, 0x96,
	0x21, 0x87, 0x21, 0x6b, 0xfb, 0x8d, 0x76, 0x8e, 0xd6, 0xf4, 0x0f, 0x63, 0xf7, 0x67, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xa1, 0x3c, 0x00, 0x72, 0x42, 0x06, 0x00, 0x00,
}
