// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: messages.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Cinema service

type CinemaService interface {
	AddCinema(ctx context.Context, in *CinemaData, opts ...client.CallOption) (*Response, error)
	DeleteCinema(ctx context.Context, in *CinemaData, opts ...client.CallOption) (*Response, error)
	GetCinemas(ctx context.Context, in *CinemaRequest, opts ...client.CallOption) (*CinemaResponse, error)
}

type cinemaService struct {
	c    client.Client
	name string
}

func NewCinemaService(name string, c client.Client) CinemaService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "cinema"
	}
	return &cinemaService{
		c:    c,
		name: name,
	}
}

func (c *cinemaService) AddCinema(ctx context.Context, in *CinemaData, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Cinema.AddCinema", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cinemaService) DeleteCinema(ctx context.Context, in *CinemaData, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Cinema.DeleteCinema", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cinemaService) GetCinemas(ctx context.Context, in *CinemaRequest, opts ...client.CallOption) (*CinemaResponse, error) {
	req := c.c.NewRequest(c.name, "Cinema.GetCinemas", in)
	out := new(CinemaResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cinema service

type CinemaHandler interface {
	AddCinema(context.Context, *CinemaData, *Response) error
	DeleteCinema(context.Context, *CinemaData, *Response) error
	GetCinemas(context.Context, *CinemaRequest, *CinemaResponse) error
}

func RegisterCinemaHandler(s server.Server, hdlr CinemaHandler, opts ...server.HandlerOption) error {
	type cinema interface {
		AddCinema(ctx context.Context, in *CinemaData, out *Response) error
		DeleteCinema(ctx context.Context, in *CinemaData, out *Response) error
		GetCinemas(ctx context.Context, in *CinemaRequest, out *CinemaResponse) error
	}
	type Cinema struct {
		cinema
	}
	h := &cinemaHandler{hdlr}
	return s.Handle(s.NewHandler(&Cinema{h}, opts...))
}

type cinemaHandler struct {
	CinemaHandler
}

func (h *cinemaHandler) AddCinema(ctx context.Context, in *CinemaData, out *Response) error {
	return h.CinemaHandler.AddCinema(ctx, in, out)
}

func (h *cinemaHandler) DeleteCinema(ctx context.Context, in *CinemaData, out *Response) error {
	return h.CinemaHandler.DeleteCinema(ctx, in, out)
}

func (h *cinemaHandler) GetCinemas(ctx context.Context, in *CinemaRequest, out *CinemaResponse) error {
	return h.CinemaHandler.GetCinemas(ctx, in, out)
}

// Client API for Movie service

type MovieService interface {
	AddMovie(ctx context.Context, in *MovieData, opts ...client.CallOption) (*Response, error)
	DeleteMovie(ctx context.Context, in *MovieData, opts ...client.CallOption) (*Response, error)
	GetMovies(ctx context.Context, in *MovieRequest, opts ...client.CallOption) (*MovieResponse, error)
}

type movieService struct {
	c    client.Client
	name string
}

func NewMovieService(name string, c client.Client) MovieService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "movie"
	}
	return &movieService{
		c:    c,
		name: name,
	}
}

func (c *movieService) AddMovie(ctx context.Context, in *MovieData, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Movie.AddMovie", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieService) DeleteMovie(ctx context.Context, in *MovieData, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Movie.DeleteMovie", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieService) GetMovies(ctx context.Context, in *MovieRequest, opts ...client.CallOption) (*MovieResponse, error) {
	req := c.c.NewRequest(c.name, "Movie.GetMovies", in)
	out := new(MovieResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Movie service

type MovieHandler interface {
	AddMovie(context.Context, *MovieData, *Response) error
	DeleteMovie(context.Context, *MovieData, *Response) error
	GetMovies(context.Context, *MovieRequest, *MovieResponse) error
}

func RegisterMovieHandler(s server.Server, hdlr MovieHandler, opts ...server.HandlerOption) error {
	type movie interface {
		AddMovie(ctx context.Context, in *MovieData, out *Response) error
		DeleteMovie(ctx context.Context, in *MovieData, out *Response) error
		GetMovies(ctx context.Context, in *MovieRequest, out *MovieResponse) error
	}
	type Movie struct {
		movie
	}
	h := &movieHandler{hdlr}
	return s.Handle(s.NewHandler(&Movie{h}, opts...))
}

type movieHandler struct {
	MovieHandler
}

func (h *movieHandler) AddMovie(ctx context.Context, in *MovieData, out *Response) error {
	return h.MovieHandler.AddMovie(ctx, in, out)
}

func (h *movieHandler) DeleteMovie(ctx context.Context, in *MovieData, out *Response) error {
	return h.MovieHandler.DeleteMovie(ctx, in, out)
}

func (h *movieHandler) GetMovies(ctx context.Context, in *MovieRequest, out *MovieResponse) error {
	return h.MovieHandler.GetMovies(ctx, in, out)
}

// Client API for Reservation service

type ReservationService interface {
	RequestReservation(ctx context.Context, in *ReservationData, opts ...client.CallOption) (*ReservationData, error)
	BookReservation(ctx context.Context, in *ReservationData, opts ...client.CallOption) (*Response, error)
	DeleteReservation(ctx context.Context, in *ReservationData, opts ...client.CallOption) (*Response, error)
	GetReservations(ctx context.Context, in *ReservationRequest, opts ...client.CallOption) (*ReservationResponse, error)
}

type reservationService struct {
	c    client.Client
	name string
}

func NewReservationService(name string, c client.Client) ReservationService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "reservation"
	}
	return &reservationService{
		c:    c,
		name: name,
	}
}

func (c *reservationService) RequestReservation(ctx context.Context, in *ReservationData, opts ...client.CallOption) (*ReservationData, error) {
	req := c.c.NewRequest(c.name, "Reservation.RequestReservation", in)
	out := new(ReservationData)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationService) BookReservation(ctx context.Context, in *ReservationData, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Reservation.BookReservation", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationService) DeleteReservation(ctx context.Context, in *ReservationData, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Reservation.DeleteReservation", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationService) GetReservations(ctx context.Context, in *ReservationRequest, opts ...client.CallOption) (*ReservationResponse, error) {
	req := c.c.NewRequest(c.name, "Reservation.GetReservations", in)
	out := new(ReservationResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Reservation service

type ReservationHandler interface {
	RequestReservation(context.Context, *ReservationData, *ReservationData) error
	BookReservation(context.Context, *ReservationData, *Response) error
	DeleteReservation(context.Context, *ReservationData, *Response) error
	GetReservations(context.Context, *ReservationRequest, *ReservationResponse) error
}

func RegisterReservationHandler(s server.Server, hdlr ReservationHandler, opts ...server.HandlerOption) error {
	type reservation interface {
		RequestReservation(ctx context.Context, in *ReservationData, out *ReservationData) error
		BookReservation(ctx context.Context, in *ReservationData, out *Response) error
		DeleteReservation(ctx context.Context, in *ReservationData, out *Response) error
		GetReservations(ctx context.Context, in *ReservationRequest, out *ReservationResponse) error
	}
	type Reservation struct {
		reservation
	}
	h := &reservationHandler{hdlr}
	return s.Handle(s.NewHandler(&Reservation{h}, opts...))
}

type reservationHandler struct {
	ReservationHandler
}

func (h *reservationHandler) RequestReservation(ctx context.Context, in *ReservationData, out *ReservationData) error {
	return h.ReservationHandler.RequestReservation(ctx, in, out)
}

func (h *reservationHandler) BookReservation(ctx context.Context, in *ReservationData, out *Response) error {
	return h.ReservationHandler.BookReservation(ctx, in, out)
}

func (h *reservationHandler) DeleteReservation(ctx context.Context, in *ReservationData, out *Response) error {
	return h.ReservationHandler.DeleteReservation(ctx, in, out)
}

func (h *reservationHandler) GetReservations(ctx context.Context, in *ReservationRequest, out *ReservationResponse) error {
	return h.ReservationHandler.GetReservations(ctx, in, out)
}

// Client API for Showing service

type ShowingService interface {
	AddShowing(ctx context.Context, in *ShowingData, opts ...client.CallOption) (*Response, error)
	DeleteShowing(ctx context.Context, in *ShowingData, opts ...client.CallOption) (*Response, error)
	GetShowings(ctx context.Context, in *ShowingRequest, opts ...client.CallOption) (*ShowingResponse, error)
}

type showingService struct {
	c    client.Client
	name string
}

func NewShowingService(name string, c client.Client) ShowingService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "showing"
	}
	return &showingService{
		c:    c,
		name: name,
	}
}

func (c *showingService) AddShowing(ctx context.Context, in *ShowingData, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Showing.AddShowing", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showingService) DeleteShowing(ctx context.Context, in *ShowingData, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Showing.DeleteShowing", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *showingService) GetShowings(ctx context.Context, in *ShowingRequest, opts ...client.CallOption) (*ShowingResponse, error) {
	req := c.c.NewRequest(c.name, "Showing.GetShowings", in)
	out := new(ShowingResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Showing service

type ShowingHandler interface {
	AddShowing(context.Context, *ShowingData, *Response) error
	DeleteShowing(context.Context, *ShowingData, *Response) error
	GetShowings(context.Context, *ShowingRequest, *ShowingResponse) error
}

func RegisterShowingHandler(s server.Server, hdlr ShowingHandler, opts ...server.HandlerOption) error {
	type showing interface {
		AddShowing(ctx context.Context, in *ShowingData, out *Response) error
		DeleteShowing(ctx context.Context, in *ShowingData, out *Response) error
		GetShowings(ctx context.Context, in *ShowingRequest, out *ShowingResponse) error
	}
	type Showing struct {
		showing
	}
	h := &showingHandler{hdlr}
	return s.Handle(s.NewHandler(&Showing{h}, opts...))
}

type showingHandler struct {
	ShowingHandler
}

func (h *showingHandler) AddShowing(ctx context.Context, in *ShowingData, out *Response) error {
	return h.ShowingHandler.AddShowing(ctx, in, out)
}

func (h *showingHandler) DeleteShowing(ctx context.Context, in *ShowingData, out *Response) error {
	return h.ShowingHandler.DeleteShowing(ctx, in, out)
}

func (h *showingHandler) GetShowings(ctx context.Context, in *ShowingRequest, out *ShowingResponse) error {
	return h.ShowingHandler.GetShowings(ctx, in, out)
}

// Client API for User service

type UserService interface {
	CreateUser(ctx context.Context, in *UserData, opts ...client.CallOption) (*Response, error)
	DeleteUser(ctx context.Context, in *UserData, opts ...client.CallOption) (*Response, error)
	GetUsers(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "user"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) CreateUser(ctx context.Context, in *UserData, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "User.CreateUser", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) DeleteUser(ctx context.Context, in *UserData, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "User.DeleteUser", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUsers(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserResponse, error) {
	req := c.c.NewRequest(c.name, "User.GetUsers", in)
	out := new(UserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	CreateUser(context.Context, *UserData, *Response) error
	DeleteUser(context.Context, *UserData, *Response) error
	GetUsers(context.Context, *UserRequest, *UserResponse) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		CreateUser(ctx context.Context, in *UserData, out *Response) error
		DeleteUser(ctx context.Context, in *UserData, out *Response) error
		GetUsers(ctx context.Context, in *UserRequest, out *UserResponse) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) CreateUser(ctx context.Context, in *UserData, out *Response) error {
	return h.UserHandler.CreateUser(ctx, in, out)
}

func (h *userHandler) DeleteUser(ctx context.Context, in *UserData, out *Response) error {
	return h.UserHandler.DeleteUser(ctx, in, out)
}

func (h *userHandler) GetUsers(ctx context.Context, in *UserRequest, out *UserResponse) error {
	return h.UserHandler.GetUsers(ctx, in, out)
}
